### PR TITLE
add minimum caching time functionnality

### PR DESCRIPTION
**Pull request by amtur8**
Add functionnality to defer polling for new changes to feed for a given time. Fix to 1 second to have an almost real time cache check.

### CODE REVIEW

**Comment by amtur8** [comment]
Hi @OleVik 

another PR for you, which will make your plugin perfect for my needs. 

As your plugin fetch RSS feed at each and every load of any page, this minimum caching time is nice to set to at least a few seconds.

Thanks in advance for any comment :)

**Comment by OleVik** [comment]
I will integrate a solution to this in version 3, which is upcoming, where a CLI-solution will be implemented for better handling of clearing and pre-building the cached feeds. Will keep the PR open until then as your code serves as a basis for limiting the polling of feeds.

**Comment by OleVik** [comment]
@amtur8 [Version 3, Release Candidate 1](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.0.0-RC1) implements this. Any testing would be appreciated.

**Comment by OleVik** [comment]
Version 3.0.1 released, which resolves the issue.

**Pull request closed without merging**
